config/routes.rb
Rails.application.routes.draw do
devise_for :users, controllers: {registration: 'registrations'}
resources :products
resources :order_items
resource :carts, only: [:show]
root to:"home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
	has_many :order_items
	def subtotal
		order_items.collect {|order_item| order_item.valid? ? (order_item.unit_price*order_item.quantity) : 0}.sum
	end

	private
	def set_subtotal
		self[:subtotal] = subtotal
end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
	belongs_to :order
	belongs_to :product

	before_save :set_unit_price
	before_save :set_total_price

	def unit_price
		if persisted?
			self[:unit_price]
		else
			product.price
		end 
	end
	def total_price
		unit_price*quantity
	end 

	private
		def set_unit_price
			self[:unit_price] = unit_price
		end

		def set_total_price
			self[:total_price] = quantity*unit_price
	    end
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :order_items
	mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception

	include ApplicationHelper 
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	def show
		@order_items = current_order.order_items
		end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@products = Product.all
  	@order_item = current_order.order_items.new
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController

	def create
		@order = current_order
		@order_item = @order.order_items.new(order_item_params)
		@order.save
		session[:order_id] = @order.id
	end
 def update
 	@oder = current_order
 	@order_item = @order.order_items.find(params[:id])
 	@order_item.update_attributes(order_item_params)
 	@order_items = @order.order_items
 end
def destroy
	@oder = current_order
 	@order_item = @order.order_items.find(params[:id])
 	@order_item.destroy
 	@order_items = @order.order_items
end
	private
	def order_item_params
		params.require(:order_item).permit(:product_id, :quantity)
end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

def index
  @products = Product.all
end
  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_path
    else
      render 'new'
  end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(product_params)
      redirect_to products_path
    else
      render 'edit'
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  private
  def product_params
    params.require(:product).permit(:brand, :model, :quantity, :size, :image, :price, :release_date )
end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	private
	def sign_up_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation)

	end
	def count_update_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)

end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def current_order
		if !session[:order_id].nil?
			Order.find(session[:order_id])
		else
			Order.new
		end
	end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/_cart_item.html.erb
<% if !@order_item.nil? && @order_item.errors.any? %>
	<ul>
		<% @order_item.errors.full_messages.each do |msg| %>
		<li> <%= msg  %> </li>
		 <% end %>
	</ul>
	<% end %>
	<% if @order_items.size>0 %>
		<% @order_items.each do |item| %>
		<div class="well">
		<div class="row">
			<div class="col-sm-5">
				<h3><%= item.product.brand %></h3>
			</div>
			<div class="col-sm-4">
				<div class="pull-right">
					<%= form_for(item, remote: true) do |f| %>
					<%= f.hidden_field :product_id, value: item.product.id %>
					<h3><%= item.product.price %></h3>
			<div class="form-group">
				<%= f.text_field :quantity, value: item.quantity.to_i, min: 1, class: 'form-control' %>
			</div>
			<div class="btn-group">
				<%= f.submit "update quantity", class: 'btn btn-primary' %>
				<%= link_to "Delete", item, method: :delete, remote: true, class: 'btn btn-danger' %>
					</div>
					<span> Total Price: <%= item.total_price %></span>
			         <% end %>
					</div>
				</div>
			</div>
		</div>
	<% end %>
   <% else %>

 <% end %>

app/views/carts/show.html.erb
 <div class="cart_item">
 	
 	<%= render "carts/cart_item" %>
 </div>

app/views/home/index.html.erb
 <h1>Sneakers for Sale</h1>

<% @products.each do |product| %>
<div class="well">
	<div class="row">
		<div class="col-sm-8">
			<h3><%= product.brand %></h3>
		</div>
		<div class="col-sm-4">
			<div class="pull-right">
				<%= form_for(@order_item, remote: true) do |f| %>
				<%= f.hidden_field :product_id, value: product.id %>
				<h5><%= product.price %></h5>
		<div class="form-group">
			<%= f.text_field :quantity, value: 1, min: 1, class: 'form-control' %>
		</div>
		<%= f.submit "Add to cart", class: 'btn btn-primary btn-sm' %>
         <% end %>
			</div>
		</div>
	</div>
</div>
<% end %>

app/views/layouts/_cart.html.erb
<%= link_to "#{current_order.order_items.size} items in a card and price #{current_order.subtotal}", carts_path %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ECommerceSneakers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">

      <!-- Static navbar -->
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Sneaker City</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li class="active"><%= link_to "Home", root_path %></li>
              
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li class="active cart"><%= render 'layouts/cart' %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>
    <%= yield %>
  </body>
</html>

app/views/order_items/create.js.erb
<% if @order.errors.any? || @order_item.errors.any? %>
alert("Invalid")
<% else %>
 $(".cart").html("<%= escape_javascript(render 'layouts/cart') %>")
<% end %>

app/views/order_items/destroy.js.erb
$(".cart").html("<%= escape_javascript(render 'layouts/cart') %>")
$("cart_item").html("<%= escape_javascript(render 'carts/cart_item') %>")

app/views/order_items/update.js.erb
$(".cart").html("<%= escape_javascript(render 'layouts/cart') %>")
$("cart_item").html("<%= escape_javascript(render 'carts/cart_item') %>")

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
 <div class="form_group">
 <%= f.label :brand,  "brand" %>
 <%= f.text_field :brand, class: 'form-control' %>
</div>

 <div class="form_group">
 <%= f.label :model,  "model" %>
 <%= f.text_field :model, class: 'form-control' %>
</div>

 <div class="form_group">
 <%= f.label :size,  "size" %>
 <%= f.number_field :size, class: 'form-control' %>
</div>

 <div class="form_group">
 <%= f.label :quantity,  "qwantity" %>
 <%= f.text_field :quantity, class: 'form-control' %>
</div>

 <div class="form_group">
 <%= f.label :price,  "price" %>
 <%= f.number_field :price, value: 1, class: 'form-control', min:1 %>
</div>

 <dev class="form_group">
	<%= f.label :image, "image" %>
	<%= f.file_field :image, multiple: true, class: 'form-control' %>
	</dev>


 <div class="form_group">
 <%= f.label :release_date,  "release_date" %>
 <%= f.datetime_field :release_date, class: 'form-control' %>
</div>

 <%= f.submit "save", class: 'btn btn-success' %>
  <% end %> 

app/views/products/edit.html.erb
<h3> Update new Sneakers</h3> 

<%= render 'form' %>

app/views/products/index.html.erb
<h3 class="text-center">Sneakers for Sale</h3>

<%= link_to "New Sneakers", new_product_path %>

<div class="row">
  <div class="col-xs-6 col-xs-offset-3">
    <table class="table">
      <tr>
        <th> brand</th>
        <th> model</th>
        <th> size</th>
        <th> quantity</th>
        <th> image</th>
        <th> price</th>
        <th> release_date</th>
        <th> Action </th>
      </tr>
    </thead>
    <tbody>
    <% @products.each do |product| %>
    <tr>
      <td><%= product.brand%></td>
      <td><%= product.model%></td>
      <td><%= product.size%></td>
      <td><%= product.quantity%></td>
      <td><%= product.image%></td>
      <td><%= product.price%></td>
      <td><%= product.release_date%></td>
       <td>
        <%= link_to "edit", edit_product_path(product)%>
       <%= link_to "Delete", product_path(product), method: :delete %>
       </td>
    </tr>
    <% end %>
    </tbody>
    </table>
  </div>
</div>

app/views/products/new.html.erb
<h3> Create new Sneakers</h3>

<%= render 'form' %>